Openqasm 3.0
comp-phys-marc/qasm-ts pull request #3
Opened 2024-10-23 18:05 UTC by seankim658

OpenQASM 3 spec update!

2024-10-30 20:02 UTC, comp-phys-marc requested changes
Cursory review. I will go more in depth in a second pass.

2024-10-31 21:42 UTC, seankim658 commented on readme.md
> +gate cphase(θ) a, b
Good point, I'll find a snippet that's shorter.

2024-10-31 21:43 UTC, seankim658 commented on src/main.ts
> +function getDetailedOutput(object) {
Thanks! This function was really useful as I continually tested and debugged output, so thought it would be useful to include as an opt-in feature.

2024-10-31 21:46 UTC, seankim658 commented on src/lexer.ts
> +export function lex(
The 2.0 lexer is mostly the same, but there are some slight tweaks from the existing master branch. Thought separating the specs similar to the qiskit implementation would be cleaner and more future proof for future OpenQASM versions but wanted the complexity of the refactor to be 1) hidden from the end user and 2) operate basically the same as the package had before rather than having people who used the existing package to know that there was a new convention in calling different versioned lexer/parsers.

2024-11-01 17:04 UTC, comp-phys-marc commented on src/lexer.ts
> +export function lex(
Yeah this is good thinking and I think that we also discussed the changes you made to the 2.0 implementation along the way. Sounds good to me.

2024-11-11 21:29 UTC, comp-phys-marc approved these changes
Thanks for all your hard work

2024-11-11 21:29 UTC, merged